import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LoginSection from '../components/login'
import ReportSection from '../components/report'
import { Button, DynamicIcon } from 'legion-ui'
import React from 'react';

class Home extends React.Component {
  state = {
    isLoggedIn: false,
  }

  handleLogin = (isLoggedIn) => this.setState({isLoggedIn})

  handleLogout = () => {
    this.setState({ isLoggedIn: false })
  }

  render() {
    const { isLoggedIn } = this.state;

    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          { isLoggedIn && (
            <>
              <Button
                className='logout-btn'
                iconRight={<DynamicIcon name="LogOut" />}
                onClick={this.handleLogout}
              >
                Logout
              </Button>
              <ReportSection />
            </>
          )}
          {
            !isLoggedIn && <LoginSection loginState={this.handleLogin} />
          }
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}

export default Home;
